### ISSUE TITLE
Debian: crystal#4204 is (still) present in debian packages

### ISSUE THREAD

**Issue by RomanHargrave** [crystal-lang/omnibus-crystal#16]
(On Debian Testing)

https://github.com/crystal-lang/crystal/issues/4204

Currently, Crystal's debian package is at commit [3c6c75e](https://github.com/crystal-lang/crystal/commit/3c6c75e) which predates the OpenSSL 1.1.0+ fix ([crystal#4230](https://github.com/crystal-lang/crystal/pull/4230)), and is therefore impossible to link without replacing the openssl package in the library with a more recent version.

**Comment by ysbaddaden** [comment]
I'm afraid you'll have to wait for a new release. Please use the master branch in the meantime —nightly builds are sadly broken.

**Comment by casper** [comment]
This still seems broken. 
I just installed crystal on Ubuntu 18.04 (crystal 0.26.1 2018-08-27) and it still fails to compile lib_ssl.cr.
